version: '3'
services:
  mysql: 
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=test
      - MYSQL_USER=sql2kv
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
